FROM scratch
LABEL MAINTAINER="heixiushamao@gmail.com"
WORKDIR /go
COPY . /go
CMD ["./main","-enviroment=production"]
#CMD ["./main","-enviroment=dp"]
#CMD ["./main","-enviroment=dt"]
#ENTRYPOINT ["./message"]

